spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/odinsync_local
    username: odinsync_local
    password: odinsync
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      format_sql: true
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

odinsync:
  security:
    jwt:
      generate-development-keys: true

logging:
  level:
    com.odinsync: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
