spring:
  datasource:
    url: ${ODINSYNC_DATASOURCE_URL}
    username: ${ODINSYNC_DATASOURCE_USERNAME}
    password: ${ODINSYNC_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

odinsync:
  security:
    jwt:
      private-key-location: ${ODINSYNC_JWT_PRIVATE_KEY_LOCATION}
      public-key-location: ${ODINSYNC_JWT_PUBLIC_KEY_LOCATION}
