spring:

  application:
    name: odinsync-platform

logging:
  level:
    root: INFO
    com.odinsync: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

odinsync:
  security:
    jwt:
      issuer: odinsync-platform
      access-token-ttl: 15m
      generate-development-keys: false
    refresh-token:
      ttl: 30d
      token-bytes: 64
